### ISSUE TITLE
Use WGS84 datum instead of WGS72

### ISSUE THREAD

**Issue by davidtgillard** [parzivail/SGP.NET#14]
I noticed that some constants are from the WGS72 geodetic datum, and not the current standard WGS84. (This is vestigial from the original SGP4 code). Depending upon what you're doing, it usually doesn't make much difference, but cheap and quick to do.

One option is to simply change the constants. Another is to allow the user to choose which datum - although I don't think there's much need for WGS72 anymore in practice, so I prefer the first option.

I'm quite happy to do it.

**Comment by parzivail** [comment]
I think it'd be best to go ahead and update to WGS84, since it's also the datum used by GPS. Thank you! Please feel free to make this change.
