### ISSUE TITLE
Bug in GroundStation.Observe - case where no next crossing point from below min elevation to above was found not handled properly

### ISSUE THREAD

**Issue by davidtgillard** [parzivail/SGP.NET#17]
In GroundStation.Observe, the present implementation of FindNextBelowToAboveCrossingPoint could potentially return a time for which the elevation of the observer is below minElevation if no such crossing point exists between the start and end times provided. 

My bug - hard to believe I didn't encounter this case before now. Anyway - fix is forthcoming.

**Comment by davidtgillard** [comment]
I'll make sure to include the case that triggered this issue in the forthcoming unit tests also.

**Comment by davidtgillard** [comment]
NuGet? 😃

**Comment by parzivail** [comment]
Just published it. Hadn't had a chance to build and publish the nupkg because of some coursework, my apologies!
