### ISSUE TITLE
Issue with caching provider and file access

### ISSUE THREAD

**Issue by Kilowhisky** [parzivail/SGP.NET#20]
Hi,

I've encountered a problem when attempting to use this library in a web application. It appears that the caching provider drops the file in the executable folder which is write protected (for good reason).  Is there a away to have it drop into a temp directory or a way to specify the directory itself?

**Comment by parzivail** [comment]
Absolutely. It should be possible to specify an absolute path instead of one relative to the executable as the filename, like so:

```csharp
var provider = new CachingRemoteTleProvider(true, TimeSpan.FromHours(12), @"C:\path\to\your\folder\cachedTles.txt", url);
```

If this doesn't work, please let me know and I'll investigate it further!

**Comment by parzivail** [comment]
Closing this for now, if you're still running into this issue, feel free to repoen it.
