### ISSUE TITLE
END TO END SIMULATION OBSERVATION

### ISSUE THREAD

**Issue by ivyselly** [parzivail/SGP.NET#27]
Hello,

please this is an enquiry, is it possible to use this tool to do an end to end simulation and configure link parameters, like gain, power and bandwidth.
i would like to observe the doppler shift and received power pairs  over a duration for my links

**Comment by parzivail** [comment]
SGP.NET doesn't simulate or estimate any of the radio parameters besides Doppler shift, so you'd have to provide that functionality yourself.
