### ISSUE TITLE
Utilize System.Uri class

### ISSUE THREAD

**Issue by ctrippel1** [parzivail/SGP.NET#4]
In SGP.NET project:
1. Replace use of the System.Security.Policy.Url class with System.Uri instead.
2. Replace use of url.Value with uri.AbsoluteUri
2. Remove System.Security.Policy usings

Files affected:
a. RemoteTleProvider.cs
b. CachingRemoteTleProvider.cs

This change has the benefit of allowing the SGP.NET project to target netstandard2.0 (i.e. .NET, .NET Core 2, etc.).

**Comment by parzivail** [comment]
Oh, boy. Fatfinger syndrome and automatic importing strikes again. Thanks for the heads up, I'll draft a fix.

**Comment by parzivail** [comment]
Released on Nuget in 1.0.4
